# Generated by Django 3.1.5 on 2021-01-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerId',
            field=models.CharField(default='customerID', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='merchantCustomerId',
            field=models.CharField(default='merchantCustomerID', max_length=50),
            preserve_default=False,
        ),
    ]
