# Generated by Django 3.1.5 on 2021-01-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paysafe', '0002_auto_20210129_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='middleName',
        ),
    ]
